# Generated by Django 2.2 on 2019-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('category', models.CharField(choices=[('other', 'other'), ('food', 'food'), ('drink', 'drink'), ('cloth', 'cloth'), ('sport', 'sport'), ('shoes', 'shoes')], default='other', max_length=20, verbose_name='category')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
